### ISSUE TITLE
Cool project,  but wondered,

### ISSUE THREAD

**Issue by FrostKnight** [smitelli/cosmore#4]
do you plan to make it so you can add, new enemies? I would also love it if you could make the boss have more hp and be harder to pin down too. :)

Let me know if you want me to try it out, I will test when its beta if you want

**Comment by smitelli** [comment]
Hi @FrostKnight, thanks for your interest in the project!

Unfortunately, it's not Cosmore's goal to add functionality that wasn't present in the original game. The core rule here is to keep this as close as possible to how Replogle's code from 1992 must have been structured while documenting things for posterity.

This isn't the only place to try, however. There is also [Cosmo-Engine](https://github.com/yuv422/cosmo-engine/) which _does_ modernize and enhance the game code. That might be a better project to contribute these types of suggestions to.

Thanks again!

**Comment by FrostKnight** [comment]
That's a shame... oh well I will try there then! 

A long time overdo, but that repo sadly seems to be all but dead...

:(
